import React, { useState, useEffect} from 'react'
import Head from 'next/head'
import { Box, Flex, VStack, Heading, Divider, Button } from '@chakra-ui/react'
import Navbar from '../components/Navbar'
import BoxUserFetch from '../components/BoxUserFetch'
import BoxSkeleton from '../components/BoxSkeleton'

//client side fetching
function Fetching() {
    const [loading, setLoading] = useState(false);
    const [users, setUsers] = useState({});
    const handleFetch = () => {
        setLoading(true)
        fetch('https://randomuser.me/api')
          .then((res) => res.json())
          .then((data) => {
            setUsers(data.results[0])
            setLoading(false)
          })
      }

    return (
        <Box>
            <Head>
                <title>Internship Program | User Fetcher</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar url="User Fetcher"/>
            <Flex flexDirection="column" minH="100vh" align="center" justify="center">
                <VStack spacing="8">
                    <Heading textAlign="center" fontSize="4xl" lineHeight="1.2">User Fetcher</Heading>
                    <Divider color="rgba(0,0,0,0.1)"/>
                    <Box paddingY="3">
                        {users.gender ? 
                            <BoxUserFetch props={users}/>
                        :   <BoxSkeleton />}
                    </Box>
                    <Divider color="rgba(0,0,0,0.1)"/>
                    <Button isLoading={loading} onClick={handleFetch} w="100%">
                        {users.gender ? "Refetch User" : "Fetch User"}
                    </Button>
                </VStack>
            </Flex>
        </Box>
    )
}

export default Fetching